name: CI-TEST-APP-DB

on: 
  push:
    branches:
      - main

jobs:
  app-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Run docker compose
        run: docker compose up -d

      - name: Test db
        run: docker exec practice-web-1 mysql -u root -p rootpassword -e "show databases;"

      - name: Test app
        run: docker exec practice-app-1 curl http://lvm66027.sit.kmutt.ac.th:5000/api/users
