name: CI-TEST-APP-DB

on: 
  push:
    branches:
      - main

jobs:
  app-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        run:  |
          docker compose up -d
          echo "Waiting for containers to initialize..."
          sleep 20

      - name: Run test inside web containers
        run: docker compose exec -it web curl http://localhost:5000/api/users

      - name: Shoutdown Docker Compose
        if: always()
        run: docker compose down
